# Uncomment this if your project is hosted on GitHub:
# github_url = https://github.com/<user or organization>/<project>/

[version]
current = "0.1.1"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "chore:bump version to {new_version}"
tag_template = "{new_version}"

# For each file to patch, add a [[file]] config section containing
# the path of the file, relative to the tbump.toml location.
[[file]]
src = "tbump.toml"

[[file]]
src = "info.plist"

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made

[[before_commit]]
name = "fetch repo"
cmd = "git fetch --all"

[[before_commit]]
name = "pull repo"
cmd = "git pull --ff-only || exit"

[[before_commit]]
name = "update changelog"
cmd = "gitchangelog > CHANGELOG.md"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"
